### ISSUE TITLE
Handle received block

### ISSUE THREAD

**Issue by cvsae** [cvsae/silme#3]
when received new blocks and tyransactions from peers sometimes exceptions.ValueError: Unterminated string starting at: line 1 column 1408 (char 1407), on restart 2-3 times it works

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 88, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 73, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 215, in doRead
    return self._dataReceived(data)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 221, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/endpoints.py", line 112, in dataReceived
    return self._wrappedProtocol.dataReceived(data)
  File "node.py", line 82, in dataReceived
    envelope = messages.read_envelope(line)
  File "/home/satoshi/silme/messages.py", line 100, in read_envelope
    return json.loads(message, encoding="latin1")
  File "/usr/lib/python2.7/json/__init__.py", line 351, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
exceptions.ValueError: Unterminated string starting at: line 1 column 1408 (char 1407)

**Comment by Aareon** [comment]
I think using SQLAlchemy might help. I can easily map out the various databases in a Pythonic manner that makes it clear to all how the databases are laid out. You might notice that I’ve opened a PR. Just let me know if you’d like me to include that there. Working on cleaning up `main.py` at this time.
